
spring:
  datasource:
    name: [ming]  #数据库名
    url: jdbc:mysql://localhost:3306/[ming]Unicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT #url
    username: root  #用户名
    password: haoming  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动